

POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "jou män",
    "author": "ossi",
    "url": "juppi blogi",
    "likes": 7,
    "userId": "5a928e2e92b2e6272ae02446"
}